name: Notify Discord

on:
  pull_request:

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"${{ github.actor }}により、Pull Request '${{ github.event.pull_request.title }}' が作成されました。\n ${{ github.event.pull_request.html_url }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
